version: '3.7'

services:

  traefik:
    image: traefik:v1.7
    ports:
      - 80:80
      - 443:443
    command:
      - --entrypoints=Name:http Address::80
      - --entrypoints=Name:https Address::443 TLS
      - --docker
      - --docker.exposedbydefault=false
      - --logLevel=DEBUG
      - --acme.email=you@mail.com
      - --acme.storage=/etc/traefik/acme.json
      - --acme.entryPoint=http
      - --acme.onHostRule=true
      - --acme.httpchallenge.entrypoint=http
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - conf:/etc/traefik

  nginx:
    image: nginx:1.17.8-alpine
    labels:
      traefik.enable: 'true'
      traefik.frontend.rule: Host:nginx.local
      traefik.frontend.entryPoints: http,https
      traefik.frontend.redirect.entryPoint: https
      traefik.port: 80

volumes:
  conf:
