version: '3.7'

services:

  nginx:
    image: nginx:1.15.8
    ports:
      - 3333:3333
      - 8082:80
    volumes:
      - ./nginx_app.conf:/etc/nginx/conf.d/default.conf

  ssh_reverse_tunneling:
    build:
      context: .
      dockerfile: Dockerfile_sshd
    ports:
      - "2222:22"
